"""Synthetic sample series, generated deterministically.

Tycheon ships **no real market data**. Exchange data is licensed, and a permissive
code licence says nothing about whether the numbers inside a CSV may be
redistributed. Rather than guess, the bundled datasets are synthetic: generated
from a seeded random-number generator, so they are redistributable by
construction, byte-for-byte reproducible, and cost nothing to store.

They are not toys. Each uses a different regime so the forecasters see the shapes
that make financial series hard:

``gbm``     constant volatility, small drift: the world a random walk is right about
``garch``   volatility clustering: calm spells and turbulent ones
``regime``  a two-state Markov switch between low and high volatility
``jump``    a diffusion with occasional large gaps

Because the data is generated by a known process, a *good* forecaster can be
checked against the truth, and an apparent edge on ``gbm`` is evidence of a bug.
Nothing about performance on synthetic data says anything about real markets.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

import numpy as np
import pandas as pd

from tycheon.data.asof import as_utc
from tycheon.data.providers.base import ProviderBase, bar_duration_for
from tycheon.data.schema import normalize_bars
from tycheon.errors import ProviderError

if TYPE_CHECKING:
    from datetime import datetime

    from numpy.typing import NDArray

Regime = Literal["gbm", "garch", "regime", "jump"]


@dataclass(frozen=True)
class SyntheticSpec:
    """Everything needed to regenerate one synthetic series exactly."""

    symbol: str
    regime: Regime
    seed: int
    periods: int
    start: str
    frequency: str = "1D"
    initial_price: float = 100.0
    #: Per-bar log-return volatility (the long-run level for ``garch``/``regime``).
    sigma: float = 0.012
    #: Per-bar log-return drift.
    drift: float = 0.0002


SAMPLE_DATASETS: dict[str, SyntheticSpec] = {
    spec.symbol: spec
    for spec in (
        SyntheticSpec("SYN-GBM", "gbm", seed=11, periods=1500, start="2018-01-01"),
        SyntheticSpec("SYN-GARCH", "garch", seed=23, periods=1500, start="2018-01-01"),
        SyntheticSpec("SYN-REGIME", "regime", seed=37, periods=1500, start="2018-01-01"),
        SyntheticSpec("SYN-JUMP", "jump", seed=41, periods=1500, start="2018-01-01"),
        SyntheticSpec(
            "SYN-GBM-H",
            "gbm",
            seed=53,
            periods=2000,
            start="2023-01-02",
            frequency="1h",
            sigma=0.004,
            drift=0.00002,
        ),
    )
}


def _log_returns(spec: SyntheticSpec, rng: np.random.Generator) -> NDArray[np.float64]:
    n, sigma = spec.periods, spec.sigma
    shocks = rng.standard_normal(n)

    if spec.regime == "gbm":
        scale = np.full(n, sigma)
    elif spec.regime == "garch":
        # GARCH(1,1) scaled so the unconditional standard deviation equals sigma.
        alpha, beta = 0.08, 0.90
        omega = sigma**2 * (1.0 - alpha - beta)
        var = np.empty(n)
        var[0] = sigma**2
        out = np.empty(n)
        out[0] = np.sqrt(var[0]) * shocks[0]
        for t in range(1, n):
            var[t] = omega + alpha * out[t - 1] ** 2 + beta * var[t - 1]
            out[t] = np.sqrt(var[t]) * shocks[t]
        return out + spec.drift
    elif spec.regime == "regime":
        calm, turbulent = 0.55 * sigma, 2.2 * sigma
        stay = {0: 0.985, 1: 0.95}
        state = 0
        scale = np.empty(n)
        for t in range(n):
            scale[t] = turbulent if state else calm
            if rng.random() > stay[state]:
                state = 1 - state
    else:  # jump
        scale = np.full(n, sigma)
        jumps = rng.random(n) < 0.01
        shocks = shocks + np.where(jumps, rng.normal(-0.2, 4.0, n), 0.0)

    return np.asarray(spec.drift + scale * shocks, dtype=np.float64)


def make_synthetic_bars(spec: SyntheticSpec) -> pd.DataFrame:
    """Generate the bars frame described by ``spec`` (no ``available_at`` yet)."""
    rng = np.random.default_rng(spec.seed)
    returns = _log_returns(spec, rng)
    close = spec.initial_price * np.exp(np.cumsum(returns))
    prev_close = np.concatenate(([spec.initial_price], close[:-1]))

    # Opens gap slightly from the previous close; the high and low stretch beyond
    # whichever of open/close is larger/smaller, so OHLC is always consistent.
    local_sigma = np.maximum(np.abs(returns), spec.sigma * 0.5)
    open_ = prev_close * np.exp(rng.normal(0.0, 0.15, spec.periods) * spec.sigma)
    high = np.maximum(open_, close) * np.exp(
        np.abs(rng.normal(0.0, 0.4, spec.periods)) * local_sigma
    )
    low = np.minimum(open_, close) * np.exp(
        -np.abs(rng.normal(0.0, 0.4, spec.periods)) * local_sigma
    )

    activity = np.abs(returns) / spec.sigma
    volume = np.round(1e6 * np.exp(0.3 * rng.standard_normal(spec.periods) + 0.25 * activity))
    amount = volume * (open_ + high + low + close) / 4.0

    if spec.frequency == "1D":
        index = pd.bdate_range(spec.start, periods=spec.periods, tz="UTC")
    else:
        index = pd.date_range(spec.start, periods=spec.periods, freq=spec.frequency, tz="UTC")
    frame = pd.DataFrame(
        {
            "open": open_,
            "high": high,
            "low": low,
            "close": close,
            "volume": volume,
            "amount": amount,
        },
        index=index,
    )
    return normalize_bars(frame, bar_duration=bar_duration_for(spec.frequency))


class SampleProvider(ProviderBase):
    """Serves the bundled synthetic series by symbol, through the normal provider guard."""

    name = "sample (synthetic)"
    license_terms = "Synthetic, generated on demand from a fixed seed. Freely redistributable."

    def _load_bars(self, symbol: str, frequency: str) -> pd.DataFrame:
        spec = SAMPLE_DATASETS.get(symbol)
        if spec is None:
            raise ProviderError(
                f"unknown sample symbol {symbol!r}; choose from {sorted(SAMPLE_DATASETS)}"
            )
        if spec.frequency != frequency:
            raise ProviderError(f"{symbol} is a {spec.frequency!r} series, not {frequency!r}")
        return make_synthetic_bars(spec)


def sample_end(symbol: str) -> pd.Timestamp:
    """The moment the last bar of a sample series became available."""
    spec = SAMPLE_DATASETS[symbol]
    last = make_synthetic_bars(spec)
    return pd.Timestamp(last["available_at"].max())


def load_sample(symbol: str, *, as_of: datetime | None = None) -> pd.DataFrame:
    """Bars for a bundled sample series as they were known at ``as_of``.

    ``as_of`` defaults to the end of the series. That default exists for the
    convenience of examples on *synthetic* data; for anything real, pass ``as_of``.
    """
    spec = SAMPLE_DATASETS.get(symbol)
    if spec is None:
        raise ProviderError(
            f"unknown sample symbol {symbol!r}; choose from {sorted(SAMPLE_DATASETS)}"
        )
    when = as_utc(as_of) if as_of is not None else sample_end(symbol)
    return SampleProvider().fetch_bars(
        symbol, start=None, end=None, as_of=when, frequency=spec.frequency
    )
